### ISSUE TITLE
Crash when setting the include buffer chests to false

### ISSUE THREAD

**Issue by Quezler** [343N/whats-missing#2]
```
46653.855 Error MainLoop.cpp:1207: Exception at tick 3575891: The mod What's Missing? (0.1.8) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event whats-missing::on_gui_click (ID 1)
__whats-missing__/control.lua:400: bad argument #2 of 3 to 'remove' (number expected, got string)
stack traceback:
	[C]: in function 'remove'
	__whats-missing__/control.lua:400: in function 'getRequestsMinusBuffer'
	__whats-missing__/control.lua:408: in function 'getRelativeRequestTable'
	__whats-missing__/control.lua:386: in function 'logisticNetworkHasUnfulfilledRequests'
	__whats-missing__/control.lua:225: in function 'updateGUI'
	__whats-missing__/control.lua:147: in function <__whats-missing__/control.lua:32>
46653.857 Error ServerMultiplayerManager.cpp:90: MultiplayerManager failed: "The mod What's Missing? (0.1.8) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event whats-missing::on_gui_click (ID 1)
__whats-missing__/control.lua:400: bad argument #2 of 3 to 'remove' (number expected, got string)
stack traceback:
	[C]: in function 'remove'
	__whats-missing__/control.lua:400: in function 'getRequestsMinusBuffer'
	__whats-missing__/control.lua:408: in function 'getRelativeRequestTable'
	__whats-missing__/control.lua:386: in function 'logisticNetworkHasUnfulfilledRequests'
	__whats-missing__/control.lua:225: in function 'updateGUI'
	__whats-missing__/control.lua:147: in function <__whats-missing__/control.lua:32>"
```

**Comment by Quezler** [comment]
screenshot of the gui, it crashes the server instantly when the checkbox is unchecked:

![Screen Shot 2020-07-16 at 22 44 50](https://user-images.githubusercontent.com/3179271/87720949-016b3580-c7b6-11ea-9a3a-65c8943583f8.png)

**Comment by 343N** [comment]
can you send me the world please? thnx

**Comment by Quezler** [comment]
luckily i kept the autosave for it on hand 😉 
[_autosave99.zip](https://github.com/343N/whats-missing/files/4935557/_autosave99.zip)
the area the screenshot was taken is at the left center side of the map:
![Screen Shot 2020-07-17 at 05 19 24](https://user-images.githubusercontent.com/3179271/87745010-1e6f2b00-c7ed-11ea-8054-2332879598a7.png)

**Comment by 343N** [comment]
thnx

**Comment by Quezler** [comment]
let me know if you were able to reproduce it, if not i could try to help out more from my end 🙂

**Comment by 343N** [comment]
table.remove does not accept non-integer table keys, that's fixed. also fixed another issue in your image where buffer chests contents were counted twice (so you get negative numbers like in your picture).

**Comment by Quezler** [comment]
thx 👍

**Comment by Quezler** [comment]
just updated the server to your new version, and now even more negatives show:
(before the reboot it was just like 2 and a half rows, now i even need to scroll)
![Screen Shot 2020-07-17 at 17 41 48](https://user-images.githubusercontent.com/3179271/87804953-e56aa100-c854-11ea-82c4-efd44ed8189b.png)

**Comment by Quezler** [comment]
[_autosave172.zip](https://github.com/343N/whats-missing/files/4938705/_autosave172.zip)
